### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by y1026** [riverloopsec/tumblerf#1]
Hello.

Do I need a hardware tool to use tumblerf?

Thanks.

**Comment by matt-knight** [comment]
As a framework, TumbleRF enables fuzzing by orchestrating the generation of test cases (Generators), the delivery of those test cases to a target (Interfaces), and monitoring their effect on the target (Harnesses).  Exactly which hardware you would need to facilitate the injection of your test cases would be informed by your application.

For instance, if your goal is to fuzz a Bluetooth chipset or device, you could enable that by adding an Interface supporting a discrete Bluetooth radio or SDR implementation.  We wrote a few Interfaces to show an example use case (802.15.4 fuzzing), so looking at those may shed some light.
